package seichedaq.slowdata;

public enum DAQDATANAMES {
	SERIALNUMBER, SUPPLYPLUS, SUPPLYMINUS, GAIN, FILTER,
	NODEID, PRESSURE, PRESSURETEMPERATURE, PRESSURESTATUS, TEMPERATURE, 
	TEMPERATURESTATUS, 
	COMPASS1ID, COMPASS1ACTIVE, COMPASS1HEADING, 
	COMPASS1PITCH, COMPASS1ROLL, COMPASS1TEMP, 
	COMPASS2ID, COMPASS2ACTIVE, COMPASS2HEADING, 
	COPMPASS2PITCH, COMPASS2ROLL, COMPASS2TEMP;
}
